name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug.
      placeholder: "A brief summary of the bug..."
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what should have happened.
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened instead.
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Specify your OS, browser, and application version.
      placeholder: |
        - OS: Windows/macOS/Linux
        - Browser: Chrome/Firefox/Edge/Safari
        - Version: v1.2.3
  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: The bug is considered resolved when these criteria are met.
      options:
        - label: Bug is reproducible
        - label: Clear error message/logs provided
        - label: Fix has been verified and tested
